language: node_js
node_js:
  - 4.2.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "Yqci15aoBvmZzyoszmYTLZim22UrK4s4lg8US+GpRzRxmMnxtw+oBItaaInoN+qay7wiLievfh+ybg6HthU35qiHsvTSTa0NzHW3uA9c38YYrN4ITStezIIQ+2gqeAJ8yIhjAV/DIipmxYaGuKquAw7hpWV88NNz3WIIE+QU6yuROt++5eD7gL0t5yfQPrpwNXAZ3aLKole2RGO85khlBODjzTAgquwyy6RJqeCUtPOYkrg0pGPZeRRIZ7tcFXfCC+Dme4MgopcgCNN4lW9952f+HfdnfxoWBkjDNzdYkv/7lZh56h41SoshHEThu3KCqH//m2BpXukwxLhsxxQfuisWkjNH2oWwGe4UcTGZvouabC+5RRUStH4TGX8Ba555b25f1X8kUpYZGGJQ3kECSfhBzgno2GWk8wgiheoP1CY4AVTtkmzfgOQD0Dnqzb+617yki5lPPVEa+dItOyyawDyDX00FpEu6vFRLy4T66JB5UdOuV59TqXyxL5xgZuDmuOFvggdxLF4FF2XQdBgfj5yicp2BRKnNB0ZPBlRCizE0b76cBtmYL/e+V4Rg6NpQHC9DpAYK2GHJotNNAFFk+//Llv6+uu2jdlVTrTSrCQfj4EfDdOhSDw2707P8EKS2wiO8eg8RWqiN3QjHnHGdlVI4y4Yk1A0rESk5SV00wYQ="